---
title: "Cleaning Offshore CTD cast Coords"
author: "Camila Vargas"
date: "10/22/2021"
output: html_document
---

Southern offshore CTD cast GPS coordinates
File Name: Koweek_et_al_Offshore_CTD_cast_coordinates.mat

Contains the following variables:
**Offshore_CTD_Lat:** Latitude of CTD casts conducted off Palmyra Atoll's southern fore reef
**Offshore_CTD_Lon:** Longitude of CTD casts conducted off Palmyra Atoll's southern fore reef

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library (plyr)
library(data.table)
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)
library(R.matlab)

## Sets R not to use scientific notations
options(scipen=999) 
```

## Read data
```{r}

ctd_coor_raw <- readMat(here::here("6.raw_data/Koweek_et_al_Offshore_CTD_cast_coordinates.mat"))

```


## Convert to DF
```{r}

df <- ctd_coor_raw %>% 
  as_tibble() %>% 
  mutate(lon = Offshore.CTD.Lon,
         lat = Offshore.CTD.Lat,
         ctd_num = paste0("offshore_ctd ", 1:7)) %>% 
  select(ctd_num, lat, lon)
  mutate(longitud = lon,
         latitud = lat) %>% 
  select(-lon, -lat, )

## Saving error: Error: `x` must not contain list or matrix columns:x invalid columns at index(s): 2 3
## Solution: use write.csv instead of write_csv

```


## Save data

```{r}

write.csv(df, here::here("7.clean_data/2012_Koweek_et_al_offshore_ctd_cast_coords.csv"), row.names = F)

```

